version: '3'
services:
  app-rest:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: i-apirest:1.0
    ports:
    - 9000:8080
    networks:
      custom_net:
        ipv4_address: 172.23.0.2

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1